---
baseurl: ""
excerpt_separator: <!--more-->
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - vendor/
sass:
  style: compressed
languages:
  de:
    baseurl: "de"
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

title: OpenMage LTS
description: A community-driven fork of Magento Community Edition
google_analytics: UA-62512293-1
show_downloads: true
theme: jekyll-theme-cayman

github: [metadata]
