---
baseurl: ""
excerpt_separator: <!--more-->
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - README.md

title: OpenMage LTS
description: A community-driven fork of Magento Community Edition
google_analytics: UA-62512293-1
show_downloads: true
theme: jekyll-theme-cayman

